version: "3.1"

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - .:/code
    environment:
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_USER: "myuser"
      POSTGRES_DB: "casanova"
  
  web:
    build: .
    restart: always
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - env
    ports:
      - "8000:8000"
    depends_on:
      - "db"
