# Generated by Django 4.1.6 on 2023-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=256, null=True)),
                ('complemento', models.CharField(blank=True, max_length=256, null=True)),
                ('bairro', models.CharField(blank=True, max_length=256, null=True)),
                ('localidade', models.CharField(blank=True, max_length=256, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('ibge', models.IntegerField(blank=True, null=True)),
                ('gia', models.IntegerField(blank=True, null=True)),
                ('ddd', models.IntegerField(blank=True, null=True)),
                ('siafi', models.IntegerField(blank=True, null=True)),
                ('lojacorr', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CEP',
                'verbose_name_plural': 'CEPs',
            },
        ),
    ]
