# Generated by Django 4.1.6 on 2023-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='gia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='ibge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='siafi',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
